controller_list:
  - name: fake_first_manipulator_controller
    joints:
      - left_arm_joint_s
      - left_arm_joint_l
      - left_arm_joint_e
      - left_arm_joint_u
      - left_arm_joint_r
      - left_arm_joint_b
      - left_arm_joint_t
  - name: fake_second_maniplurator_controller
    joints:
      - right_arm_joint_s
      - right_arm_joint_l
      - right_arm_joint_e
      - right_arm_joint_u
      - right_arm_joint_r
      - right_arm_joint_b
      - right_arm_joint_t
  - name: fake_dual_manipulator_controller
    joints:
      - left_arm_joint_s
      - left_arm_joint_l
      - left_arm_joint_e
      - left_arm_joint_u
      - left_arm_joint_r
      - left_arm_joint_b
      - left_arm_joint_t
      - right_arm_joint_s
      - right_arm_joint_l
      - right_arm_joint_e
      - right_arm_joint_u
      - right_arm_joint_r
      - right_arm_joint_b
      - right_arm_joint_t